### ISSUE TITLE
Â?

### ISSUE THREAD

**Issue by lovebes** [noopkat/twitch-scripts#1]
Hi Noopkat, thanks for the in-depth description of your setup in : https://medium.com/@suzhinton/my-twitch-live-coding-setup-b2516672fb21

Quick question. What's the "Â" in your Applescript? Is it a typo?

**Comment by noopkat** [comment]
Hi thanks for the question. They’re special line breaks that AppleScript Editor can parse. AppleScript is newline sensitive so you can’t just hit the enter key to break up long lines for readability reasons. 

They look weird when viewing the source code on GitHub but in the AppleScript Editor they display like little enter key arrows.
